project:
  type: book

number-depth: 2

book:
  title: "MHC in DC Independent Study Guide"
  subtitle: "Fall 2026"
  author: "Adam Hilton"
  sidebar:
    style: docked
    background: light
  page-navigation: true
  page-footer: "MHC in DC Indepedent Study"
  favicon: logo.png
  image: logo.png
  cover-image: logo.png
  downloads: [pdf, docx]
  search: true
  chapters:
    - index.qmd
    - big_picture.qmd
    - topic_to_question.qmd
    - lit_review.qmd
    - theory_and_hypothesis.qmd
    - research_design.qmd
    - research_proposal.qmd
    - proposal_to_paper.qmd
    - data_collection_analysis.qmd
    - findings_and_implications.qmd
    - research_paper.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    fig-width: 6
    fig-asp: 0.618
    out-width: "70%"
    fig-align: center
  epub:
    cover-image: logo.png
  typst:
    theme: default

editor: visual

