# Welcome! {.unnumbered}

This is an online guide for Mount Holyoke students undertaking an independent study (POLIT 395) while spending the fall semester living, learning, and interning in Washington, DC.

As an integral part of the DC program, the independent study offers you the opportunity to take a deep dive into a political science-related topic of your choice. This guide offers step-by-step advice to assist you as you develop your project from an initial idea to a polished research paper.

## What's in this guide?

This guide begins by providing you with the **big picture** of the research process. Like researchers in other social science disciplines, such as economics or sociology, political scientists ultimately want to **explain** aspects of the social and political world. What sets political scientists apart from journalists, pundits, or other political commentators is our commitment to transparency. When it comes to social science research, it's not just *what* you found that's important but also *how* you found it.

Additionally, while understanding of the political world is valuable for its own sake, an underlying motivation for most political scientists is to understand the world *in order to make it better*. Thus, a common focus of most social science is **problem-oriented research**: our work begins with a problem or puzzle of general concern which requires better understanding if society is to respond effectively.

Fortunately, we don't need to tackle these big problems on our own. Social scientists undertake research within communities of likeminded scholars who research similar or sometimes the same problem or puzzle as us. By **joining these ongoing conversations**, we benefit from generations of past and contemporary scholars, inheriting the accumulated knowledge of the discipline, and drawing inspiration and ideas from it as we make our own modest contribution.

Specifically, despite the apparent novelties of things like Artificial Intelligence (AI) or the presidency of Donald Trump, very few things in our world are actually brand new. Though it may be true that AI is a very distinctive kind of technology, and that there's never been an American president quite like Donald Trump, they are both instances of broader phenomena: disruptive innovations on the one hand; right-wing populists on the other. What's useful about looking at new developments in this way is that there is usually some existing **theory** to draw on when trying to explain them. By turning to the existing literature, we can learn how to think abstractly about, say, how disruptive innovations are likely to affect wealth disparities, or about how populist presidents are likely to challenge institutional checks and balances. Whether we are applying existing theory to new problems or creating a new theory from scratch, thinking abstractly about concepts and their relationships provides us with a preliminary understanding of novel people, processes, and events.

To see if a theory actually helps us explain the political problems that concern us, we need to draw out some empirical implications, or **hypotheses**, to test. To do so, we simply ask ourselves:

> *if this theory is true, what would I expect to see in the world?*

Our strategy for **collecting the** **evidence or data** we need to test our hypotheses is called our **research design**. Specifying precisely how we collected our data and tested our hypotheses is a critical part of research because it is a process containing myriad decisions on the part of the researcher—some small, others large—none of answers for which are obvious and all of which a critical reader may scrutinize. If, say, you're interested in explaining the affect of AI on inequality, how will you define and measure those two concepts? There are multiple legitimate ways to do so, so why did you do it in *that* particular way? Again, it's not just what you found that matters in social science, it's *how* you found it.

As this brief summary implies, social science research takes a significant amount of effort and hard work. But the rewards can be personally edifying and professionally rewarding. The **findings and implications** of our research can change the way we, and maybe even others, understand and intervene in the world. We may even be able to make it better.

## How to use this guide

This guide is meant to serve as a learning resource and reference material for you as you chart the path of your independent study from start to finish. In it you'll find chapters that progressively walk you through the research workflow from begging to end, ranging from ideas about how to get started to detailed instructions about how to format your final paper.

The chapters are accompanied by short asynchronous lectures posted to Canvas. These are meant to clarify and amplify specific parts of the readings, not replace them, so be sure to consult both resources throughout the semester.

On Canvas you'll also find links to upload your work. Details regarding due dates can be found in the course syllabus.
